server:
  port: 8085
spring:
  application:
    name: fraud-detection-service

info:
  application:
    name: ${spring.application.name}
    description: '@project.description@'
    version: '@project.version@'
    spring-cloud-version: '@spring-cloud.version@'
    spring-boot-version: '@project.parent.version@'